# Generated by Django 5.1.3 on 2025-01-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
